// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/git-credential-oauth/internal/credential"
	"github.com/nicholas-fedor/git-credential-oauth/internal/get"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGetter
func (_mock *MockGetter) Get(ctx context.Context, req credential.Request, opts get.Options) (credential.Response, error) {
	ret := _mock.Called(ctx, req, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 credential.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, credential.Request, get.Options) (credential.Response, error)); ok {
		return returnFunc(ctx, req, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, credential.Request, get.Options) credential.Response); ok {
		r0 = returnFunc(ctx, req, opts)
	} else {
		r0 = ret.Get(0).(credential.Response)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, credential.Request, get.Options) error); ok {
		r1 = returnFunc(ctx, req, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req credential.Request
//   - opts get.Options
func (_e *MockGetter_Expecter) Get(ctx any, req any, opts any) *MockGetter_Get_Call {
	return &MockGetter_Get_Call{Call: _e.mock.On("Get", ctx, req, opts)}
}

func (_c *MockGetter_Get_Call) Run(run func(ctx context.Context, req credential.Request, opts get.Options)) *MockGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 credential.Request
		if args[1] != nil {
			arg1 = args[1].(credential.Request)
		}
		var arg2 get.Options
		if args[2] != nil {
			arg2 = args[2].(get.Options)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGetter_Get_Call) Return(response credential.Response, err error) *MockGetter_Get_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockGetter_Get_Call) RunAndReturn(run func(ctx context.Context, req credential.Request, opts get.Options) (credential.Response, error)) *MockGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}
