// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigReader creates a new instance of MockConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigReader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConfigReader is an autogenerated mock type for the ConfigReader type
type MockConfigReader struct {
	mock.Mock
}

type MockConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigReader) EXPECT() *MockConfigReader_Expecter {
	return &MockConfigReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockConfigReader
func (_mock *MockConfigReader) Get(ctx context.Context, key string, rawURL string) (string, bool, error) {
	ret := _mock.Called(ctx, key, rawURL)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return returnFunc(ctx, key, rawURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, key, rawURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, key, rawURL)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, key, rawURL)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConfigReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfigReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - rawURL string
func (_e *MockConfigReader_Expecter) Get(ctx any, key any, rawURL any) *MockConfigReader_Get_Call {
	return &MockConfigReader_Get_Call{Call: _e.mock.On("Get", ctx, key, rawURL)}
}

func (_c *MockConfigReader_Get_Call) Run(run func(ctx context.Context, key string, rawURL string)) *MockConfigReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigReader_Get_Call) Return(value string, found bool, err error) *MockConfigReader_Get_Call {
	_c.Call.Return(value, found, err)
	return _c
}

func (_c *MockConfigReader_Get_Call) RunAndReturn(run func(ctx context.Context, key string, rawURL string) (string, bool, error)) *MockConfigReader_Get_Call {
	_c.Call.Return(run)
	return _c
}
