// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBrowser creates a new instance of MockBrowser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBrowser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBrowser is an autogenerated mock type for the Browser type
type MockBrowser struct {
	mock.Mock
}

type MockBrowser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowser) EXPECT() *MockBrowser_Expecter {
	return &MockBrowser_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockBrowser
func (_mock *MockBrowser) Open(ctx context.Context, targetURL string) error {
	ret := _mock.Called(ctx, targetURL)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, targetURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrowser_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockBrowser_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - targetURL string
func (_e *MockBrowser_Expecter) Open(ctx any, targetURL any) *MockBrowser_Open_Call {
	return &MockBrowser_Open_Call{Call: _e.mock.On("Open", ctx, targetURL)}
}

func (_c *MockBrowser_Open_Call) Run(run func(ctx context.Context, targetURL string)) *MockBrowser_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrowser_Open_Call) Return(err error) *MockBrowser_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrowser_Open_Call) RunAndReturn(run func(ctx context.Context, targetURL string) error) *MockBrowser_Open_Call {
	_c.Call.Return(run)
	return _c
}
