// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCallback creates a new instance of MockCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallback {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCallback is an autogenerated mock type for the Callback type
type MockCallback struct {
	mock.Mock
}

type MockCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCallback) EXPECT() *MockCallback_Expecter {
	return &MockCallback_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCallback
func (_mock *MockCallback) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCallback_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCallback_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCallback_Expecter) Close() *MockCallback_Close_Call {
	return &MockCallback_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCallback_Close_Call) Run(run func()) *MockCallback_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCallback_Close_Call) Return(err error) *MockCallback_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCallback_Close_Call) RunAndReturn(run func() error) *MockCallback_Close_Call {
	_c.Call.Return(run)
	return _c
}

// RedirectURL provides a mock function for the type MockCallback
func (_mock *MockCallback) RedirectURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RedirectURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCallback_RedirectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedirectURL'
type MockCallback_RedirectURL_Call struct {
	*mock.Call
}

// RedirectURL is a helper method to define mock.On call
func (_e *MockCallback_Expecter) RedirectURL() *MockCallback_RedirectURL_Call {
	return &MockCallback_RedirectURL_Call{Call: _e.mock.On("RedirectURL")}
}

func (_c *MockCallback_RedirectURL_Call) Run(run func()) *MockCallback_RedirectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCallback_RedirectURL_Call) Return(s string) *MockCallback_RedirectURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCallback_RedirectURL_Call) RunAndReturn(run func() string) *MockCallback_RedirectURL_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockCallback
func (_mock *MockCallback) Wait(ctx context.Context) (url.Values, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 url.Values
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (url.Values, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) url.Values); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(url.Values)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCallback_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockCallback_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCallback_Expecter) Wait(ctx any) *MockCallback_Wait_Call {
	return &MockCallback_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockCallback_Wait_Call) Run(run func(ctx context.Context)) *MockCallback_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCallback_Wait_Call) Return(values url.Values, err error) *MockCallback_Wait_Call {
	_c.Call.Return(values, err)
	return _c
}

func (_c *MockCallback_Wait_Call) RunAndReturn(run func(ctx context.Context) (url.Values, error)) *MockCallback_Wait_Call {
	_c.Call.Return(run)
	return _c
}
