// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/git-credential-oauth/internal/oauth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCallbackFactory creates a new instance of MockCallbackFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallbackFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallbackFactory {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCallbackFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCallbackFactory is an autogenerated mock type for the CallbackFactory type
type MockCallbackFactory struct {
	mock.Mock
}

type MockCallbackFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCallbackFactory) EXPECT() *MockCallbackFactory_Expecter {
	return &MockCallbackFactory_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockCallbackFactory
func (_mock *MockCallbackFactory) Start(ctx context.Context, redirectURL string) (oauth.Callback, error) {
	ret := _mock.Called(ctx, redirectURL)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 oauth.Callback
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (oauth.Callback, error)); ok {
		return returnFunc(ctx, redirectURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) oauth.Callback); ok {
		r0 = returnFunc(ctx, redirectURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth.Callback)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, redirectURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCallbackFactory_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCallbackFactory_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - redirectURL string
func (_e *MockCallbackFactory_Expecter) Start(ctx any, redirectURL any) *MockCallbackFactory_Start_Call {
	return &MockCallbackFactory_Start_Call{Call: _e.mock.On("Start", ctx, redirectURL)}
}

func (_c *MockCallbackFactory_Start_Call) Run(run func(ctx context.Context, redirectURL string)) *MockCallbackFactory_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCallbackFactory_Start_Call) Return(callback oauth.Callback, err error) *MockCallbackFactory_Start_Call {
	_c.Call.Return(callback, err)
	return _c
}

func (_c *MockCallbackFactory_Start_Call) RunAndReturn(run func(ctx context.Context, redirectURL string) (oauth.Callback, error)) *MockCallbackFactory_Start_Call {
	_c.Call.Return(run)
	return _c
}
