// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// PromptDevice provides a mock function for the type MockPrompter
func (_mock *MockPrompter) PromptDevice(ctx context.Context, userCode string, verificationURI string, verificationURIComplete string) error {
	ret := _mock.Called(ctx, userCode, verificationURI, verificationURIComplete)

	if len(ret) == 0 {
		panic("no return value specified for PromptDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userCode, verificationURI, verificationURIComplete)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrompter_PromptDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptDevice'
type MockPrompter_PromptDevice_Call struct {
	*mock.Call
}

// PromptDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userCode string
//   - verificationURI string
//   - verificationURIComplete string
func (_e *MockPrompter_Expecter) PromptDevice(ctx any, userCode any, verificationURI any, verificationURIComplete any) *MockPrompter_PromptDevice_Call {
	return &MockPrompter_PromptDevice_Call{Call: _e.mock.On("PromptDevice", ctx, userCode, verificationURI, verificationURIComplete)}
}

func (_c *MockPrompter_PromptDevice_Call) Run(run func(ctx context.Context, userCode string, verificationURI string, verificationURIComplete string)) *MockPrompter_PromptDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPrompter_PromptDevice_Call) Return(err error) *MockPrompter_PromptDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrompter_PromptDevice_Call) RunAndReturn(run func(ctx context.Context, userCode string, verificationURI string, verificationURIComplete string) error) *MockPrompter_PromptDevice_Call {
	_c.Call.Return(run)
	return _c
}
