// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/git-credential-oauth/internal/helper"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHelper creates a new instance of MockHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelper {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHelper is an autogenerated mock type for the Helper type
type MockHelper struct {
	mock.Mock
}

type MockHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelper) EXPECT() *MockHelper_Expecter {
	return &MockHelper_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function for the type MockHelper
func (_mock *MockHelper) Configure(ctx context.Context, opts helper.Options) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.Options) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHelper_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockHelper_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - ctx context.Context
//   - opts helper.Options
func (_e *MockHelper_Expecter) Configure(ctx any, opts any) *MockHelper_Configure_Call {
	return &MockHelper_Configure_Call{Call: _e.mock.On("Configure", ctx, opts)}
}

func (_c *MockHelper_Configure_Call) Run(run func(ctx context.Context, opts helper.Options)) *MockHelper_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.Options
		if args[1] != nil {
			arg1 = args[1].(helper.Options)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHelper_Configure_Call) Return(err error) *MockHelper_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHelper_Configure_Call) RunAndReturn(run func(ctx context.Context, opts helper.Options) error) *MockHelper_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Unconfigure provides a mock function for the type MockHelper
func (_mock *MockHelper) Unconfigure(ctx context.Context, opts helper.Options) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Unconfigure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, helper.Options) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHelper_Unconfigure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unconfigure'
type MockHelper_Unconfigure_Call struct {
	*mock.Call
}

// Unconfigure is a helper method to define mock.On call
//   - ctx context.Context
//   - opts helper.Options
func (_e *MockHelper_Expecter) Unconfigure(ctx any, opts any) *MockHelper_Unconfigure_Call {
	return &MockHelper_Unconfigure_Call{Call: _e.mock.On("Unconfigure", ctx, opts)}
}

func (_c *MockHelper_Unconfigure_Call) Run(run func(ctx context.Context, opts helper.Options)) *MockHelper_Unconfigure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 helper.Options
		if args[1] != nil {
			arg1 = args[1].(helper.Options)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHelper_Unconfigure_Call) Return(err error) *MockHelper_Unconfigure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHelper_Unconfigure_Call) RunAndReturn(run func(ctx context.Context, opts helper.Options) error) *MockHelper_Unconfigure_Call {
	_c.Call.Return(run)
	return _c
}
