// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDebugGate creates a new instance of MockDebugGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebugGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebugGate {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDebugGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDebugGate is an autogenerated mock type for the DebugGate type
type MockDebugGate struct {
	mock.Mock
}

type MockDebugGate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebugGate) EXPECT() *MockDebugGate_Expecter {
	return &MockDebugGate_Expecter{mock: &_m.Mock}
}

// Set provides a mock function for the type MockDebugGate
func (_mock *MockDebugGate) Set(enabled bool) {
	_mock.Called(enabled)
	return
}

// MockDebugGate_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockDebugGate_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - enabled bool
func (_e *MockDebugGate_Expecter) Set(enabled any) *MockDebugGate_Set_Call {
	return &MockDebugGate_Set_Call{Call: _e.mock.On("Set", enabled)}
}

func (_c *MockDebugGate_Set_Call) Run(run func(enabled bool)) *MockDebugGate_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDebugGate_Set_Call) Return() *MockDebugGate_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDebugGate_Set_Call) RunAndReturn(run func(enabled bool)) *MockDebugGate_Set_Call {
	_c.Run(run)
	return _c
}
