// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/git-credential-oauth/internal/forge"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Lookup(host string) (forge.Client, bool) {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 forge.Client
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (forge.Client, bool)); ok {
		return returnFunc(host)
	}
	if returnFunc, ok := ret.Get(0).(func(string) forge.Client); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Get(0).(forge.Client)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(host)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRegistry_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockRegistry_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - host string
func (_e *MockRegistry_Expecter) Lookup(host any) *MockRegistry_Lookup_Call {
	return &MockRegistry_Lookup_Call{Call: _e.mock.On("Lookup", host)}
}

func (_c *MockRegistry_Lookup_Call) Run(run func(host string)) *MockRegistry_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_Lookup_Call) Return(client forge.Client, b bool) *MockRegistry_Lookup_Call {
	_c.Call.Return(client, b)
	return _c
}

func (_c *MockRegistry_Lookup_Call) RunAndReturn(run func(host string) (forge.Client, bool)) *MockRegistry_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// SelfHosted provides a mock function for the type MockRegistry
func (_mock *MockRegistry) SelfHosted(kind forge.Kind) bool {
	ret := _mock.Called(kind)

	if len(ret) == 0 {
		panic("no return value specified for SelfHosted")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(forge.Kind) bool); ok {
		r0 = returnFunc(kind)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRegistry_SelfHosted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelfHosted'
type MockRegistry_SelfHosted_Call struct {
	*mock.Call
}

// SelfHosted is a helper method to define mock.On call
//   - kind forge.Kind
func (_e *MockRegistry_Expecter) SelfHosted(kind any) *MockRegistry_SelfHosted_Call {
	return &MockRegistry_SelfHosted_Call{Call: _e.mock.On("SelfHosted", kind)}
}

func (_c *MockRegistry_SelfHosted_Call) Run(run func(kind forge.Kind)) *MockRegistry_SelfHosted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 forge.Kind
		if args[0] != nil {
			arg0 = args[0].(forge.Kind)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_SelfHosted_Call) Return(b bool) *MockRegistry_SelfHosted_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRegistry_SelfHosted_Call) RunAndReturn(run func(kind forge.Kind) bool) *MockRegistry_SelfHosted_Call {
	_c.Call.Return(run)
	return _c
}
