// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGitRunner creates a new instance of MockGitRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitRunner {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGitRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGitRunner is an autogenerated mock type for the GitRunner type
type MockGitRunner struct {
	mock.Mock
}

type MockGitRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitRunner) EXPECT() *MockGitRunner_Expecter {
	return &MockGitRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockGitRunner
func (_mock *MockGitRunner) Run(ctx context.Context, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockGitRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...string
func (_e *MockGitRunner_Expecter) Run(ctx any, args ...any) *MockGitRunner_Run_Call {
	return &MockGitRunner_Run_Call{Call: _e.mock.On("Run",
		append([]any{ctx}, args...)...)}
}

func (_c *MockGitRunner_Run_Call) Run(run func(ctx context.Context, args ...string)) *MockGitRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockGitRunner_Run_Call) Return(err error) *MockGitRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitRunner_Run_Call) RunAndReturn(run func(ctx context.Context, args ...string) error) *MockGitRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
